version: '3.3'
services:
  pg:
    container_name: ms25-db1
    image: postgres
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ms25
      POSTGRES_PASSWORD: password


volumes:
  db_data: { }