spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/ms25
    username: ms25
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

